name: termlib
description: Library that provides a set of utilities for terminal applications.
version: 0.4.0
repository: https://github.com/kascote/termkit/tree/main/packages/termlib
homepage: https://github.com/kascote/termkit
issue_tracker: https://github.com/kascote/termkit/issues
documentation: https://github.com/kascote/termkit/tree/master/packages/termlib#readme
topics: [console, terminal, tui, ansi]
platforms:
  linux:
  macos:

environment:
  sdk: ">=3.9.2 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  ffi: ^2.1.0
  meta: ^1.15.0
  termansi: ^0.3.1
  termparser: ^0.3.0
  win32: ^5.5.3

dev_dependencies:
  coverage: ^1.7.2
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0
  vm_service: ^14.2.5
