name: termparser
description: ANSI Terminal escape sequence parser for terminal applications.
version: 0.3.0
repository: https://github.com/kascote/termkit/tree/master/packages/termparser
homepage: https://github.com/kascote/termkit
issue_tracker: https://github.com/kascote/termkit/issues
documentation: https://github.com/kascote/termkit/tree/master/packages/termparser#readme
topics: [console, terminal, ansi, parser]
platforms:
  linux:
  macos:

environment:
  sdk: ">=3.9.2 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  meta: ^1.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0
